### ISSUE TITLE
Why didn't my @RabbitListener automatically create exchange, queue???

### ISSUE THREAD

**Issue by Mrliangwenbin** [yutiansut/QAPUBSUB#4]
@RabbitListener(bindings = @QueueBinding(
            value = @Queue(name = "liang.sms.verify.queue"),
            exchange = @Exchange(name = "liang.sms.exchange", type = ExchangeTypes.TOPIC),
            key = "sms.verify.code"
    ))
My rabbitmq is installed in the cloud.

**Comment by yutiansut** [comment]
@Mrliangwenbin 不知道 另外你的腾讯云服务器的mysql数据库的密码不要明文传到github撒 太危险了https://github.com/Mrliangwenbin/config_repo/blob/master/photography-test.yml#L7
